[pytest]
markers =
    smoke: smoke tests - critical functionality
    regression: edge cases and functionality not included on smoke
    e2e: end-to-end tests

testpaths = tests
python_files = test_*.py
python_functions = test_*

addopts =
    -v
    -s
    --strict-markers
    --html=reports/report.html
    --self-contained-html
    --alluredir=allure-results
    --clean-alluredir
    

log_cli = true
log_cli_level = INFO
